### ISSUE TITLE
main.jade

### ISSUE THREAD

**Issue by RobertoAF** [UniStudentCollective-TurtleRunners/UniversalStudentCollective#4]
We need to redo the main page.

As we saw with Craigslist, we need to add tiles for each of our ten functionalities.

Any ideas about how to design this would be appreciated. Should we include the search field and display the tiles as seen here:

<img src="https://cloud.githubusercontent.com/assets/13029161/23088844/a4dbd424-f535-11e6-84e6-7975415a6a79.png">

Or, should we only display the tiles?

**Comment by yparks** [comment]
The screenshot was exactly what I thought of our home page. but for now, like we said , we don't need worry about the pics yet right ?

**Comment by RobertoAF** [comment]
That's right. At the moment, we just need to create the tiles.  We can add a text link at the top and leave the images blank for now.

Here's an interesting example of tiles with separate colors, which is another option we can consider.
<img src="https://cloud.githubusercontent.com/assets/13029161/23088930/bdc24850-f536-11e6-80bc-ca9357729353.png">

**Comment by potatoyenn** [comment]
@RobertoAF is this from twitter?

**Comment by RobertoAF** [comment]
@potatoyenn Bootstrap was designed at twitter, so I think it's a bootstrap template.
Check out some example code:
http://talkslab.github.io/metro-bootstrap/components.html
