### ISSUE TITLE
Log-in/Sign-up

### ISSUE THREAD

**Issue by RobertoAF** [UniStudentCollective-TurtleRunners/UniversalStudentCollective#77]
Hey Nell,

I made some additions to the sign-up form. I took out the labels on the main form to make it more compact.
I also added different colors so that we can get a better idea of what could work for our main page.
In terms of layout, let me know if we can add/take out anything before we do a code review and then make a merge. Do you think we could add a photo or a description on the left side?

![screen shot 2017-04-08 at 9 04 15 pm](https://cloud.githubusercontent.com/assets/13029161/24834586/0b1efea6-1c9f-11e7-9e84-6733a2c37f27.png)

**Comment by ndosker** [comment]
![websitescreenshot](https://cloud.githubusercontent.com/assets/22584461/24834775/b1b05b30-1ca3-11e7-855d-b4e7771f2016.png)
Example of a list of benefits that would be to the left of the sign up div

**Comment by RobertoAF** [comment]
@ndosker Cool, I like that idea! For now, I think we need to get this form in for back-end people to test the schema/database. So, in terms of layout, is there anything else that we need to add/alter/remove?

@ndosker @potatoyenn @ideheer @yparks 
Would anyone be interested in doing the write up for the list of benefits?

**Comment by ndosker** [comment]
@RobertoAF @potatoyenn @ideheer @yparks I'm up for doing it. I'll write it in here when I'm done (or in the group chat, whichever is better)

**Comment by RobertoAF** [comment]
@ndosker 
Cool. If the layout looks fine, do you mind if we do the code review first, convert the file to jade, and then do a pull request first before doing the write up? That way we will at least have the log-in finished tonight in case back-end needs to use it, and then make changes today-tomorrow in terms of the write-up.

I can send you the codepen.io file.

**Comment by ndosker** [comment]
Sure

**Comment by RobertoAF** [comment]
@ndosker @potatoyenn @ideheer @yparks 
Thanks Nell! Looks fabulous!
![screen shot 2017-04-08 at 10 53 18 pm](https://cloud.githubusercontent.com/assets/13029161/24835152/3686ee3c-1cae-11e7-8d1a-be60c909c2c2.png)

**Comment by ndosker** [comment]
![noallergies](https://cloud.githubusercontent.com/assets/22584461/24835678/987dd584-1cbc-11e7-9b92-923973d9f4e4.png)
![yesallergies](https://cloud.githubusercontent.com/assets/22584461/24835679/987fe6c6-1cbc-11e7-857a-180f7dbfbb9b.png)

**Comment by RobertoAF** [comment]
@ndosker 
Brava!
