### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by RobertoAF** [UniStudentCollective-TurtleRunners/UniversalStudentCollective#78]
@potatoyenn @ndosker @ideheer @yparks 

Hey guys, it's navigation bar color selection time!

I just wanted to let you know that I am planning on sending out an anonymous feedback form so that we can choose our colors [for our log-in/sign-up page and the navigation bar of our main site]. You can see the items I will be adding to the list below. To accommodate everyone, please post (on this page) the hex # of up to three additional colors you would like to be added to the list by 9AM tomorrow morning, Monday, April 10th, 2017.

If you are fine with the options below, then don't worry about it.

[http://www.htmlcsscolor.com/hex/4A0620](url)

![screen shot 2017-04-08 at 10 53 18 pm](https://cloud.githubusercontent.com/assets/13029161/24841547/eda869a0-1d3b-11e7-9538-785b009dc70e.png)
![screen shot 2017-04-09 at 3 02 12 pm](https://cloud.githubusercontent.com/assets/13029161/24841550/efd7ee8a-1d3b-11e7-90ed-bba0bd649c20.png)
![screen shot 2017-04-09 at 3 05 31 pm](https://cloud.githubusercontent.com/assets/13029161/24841551/f15ae47e-1d3b-11e7-8b80-5685882e903a.png)
![screen shot 2017-04-09 at 3 06 52 pm](https://cloud.githubusercontent.com/assets/13029161/24841552/f3cfb608-1d3b-11e7-86b4-3e4c8cda528c.png)
![screen shot 2017-04-09 at 3 12 10 pm](https://cloud.githubusercontent.com/assets/13029161/24841555/f7bbf7b8-1d3b-11e7-8265-fd43d884108d.png)
![screen shot 2017-04-09 at 3 14 45 pm](https://cloud.githubusercontent.com/assets/13029161/24841556/faf9d1de-1d3b-11e7-937c-5bc7aaee9814.png)
![screen shot 2017-04-09 at 3 18 42 pm](https://cloud.githubusercontent.com/assets/13029161/24841557/000122ea-1d3c-11e7-82dc-532837d7aabd.png)
![screen shot 2017-04-09 at 3 35 54 pm](https://cloud.githubusercontent.com/assets/13029161/24841615/0f19bef8-1d3d-11e7-867f-607f0b8480db.png)
![screen shot 2017-04-09 at 3 36 04 pm](https://cloud.githubusercontent.com/assets/13029161/24841616/10db05a8-1d3d-11e7-8341-afc2980603d1.png)

**Comment by ideheer** [comment]
I like options 1, 2, 3, and 4 the best. 
#colorblind

**Comment by ndosker** [comment]
My picks are 1, 4, and 8

**Comment by RobertoAF** [comment]
If you have any colors that you would like to add to this list, please post their hexadecimal #  by tomorrow morning. Thanks.

**Comment by RobertoAF** [comment]
I have a personal proposal that I think could work. Hex #FF0080:
![yl1gz](https://cloud.githubusercontent.com/assets/13029161/24842362/b0cbb040-1d4b-11e7-9db4-0faf50993023.jpg)

**Comment by ndosker** [comment]
Admittedly I'm a fan of the more subdued colors, but that's just me

**Comment by RobertoAF** [comment]
:p

**Comment by yparks** [comment]
3,6,8 I think is good.

**Comment by RobertoAF** [comment]
I like 4, 6 and 8.
